### ISSUE TITLE
VPNV6 support

### ISSUE THREAD

**Issue by su1329** [OpenBMP/obmp-collector#5]
Hello,
Are there any plans to add VPNV6 support?

**Comment by TimEvens** [comment]
VPNv6 is supported today.  Are you not seeing any data for it?

**Comment by su1329** [comment]
I have built through Docker-compose, which does not yet support vpnv6

**Comment by TimEvens** [comment]
When you say it's not supported, that's incorrect. I'll update the README.  [VPNv4 and VPN6 is there](https://github.com/OpenBMP/obmp-collector/blob/main/Server/src/bgp/MPReachAttr.cpp#L218). Last tests with VPNv4 and VPNv6 where parsing and inserting data into PSQL fine. 

Can you provide:

1. The openbmpd log
2. If possible, can you provide a packet capture of the BMP TCP stream/data?  I'll be able to use the pcap to replay/analyze it.

**Comment by TimEvens** [comment]
README updated. Please re-open if you are running into vpnv6 collector/psql-app issues.
