### ISSUE TITLE
isprepolicy and isadjribin set to False for all prefixes

### ISSUE THREAD

**Issue by v1shnya** [OpenBMP/obmp-collector#6]
Hi Tim, great product! start to test it in my lab
Let me contact you on an issue that I see with Juniper and Huawei devices - isprepolicy and isadjribin flags are alwayes set to False for any prefixes!!!

Configured Huawei box
![image](https://user-images.githubusercontent.com/113546041/190336450-f4371b48-6b93-4eaf-93fc-8f25eb876870.png)

Look at the Frame 35. It's Adj-RIB-In for the prefix 1.100.11.1
![Frame_35](https://user-images.githubusercontent.com/113546041/190336106-24cf38bc-9bed-4196-995c-60e2a88903d8.jpg)
at the same time in Postgress it's mentioned as Adj-RIB-Out
![image](https://user-images.githubusercontent.com/113546041/190336795-68b8d486-fcdd-478a-b8ec-edccac3c9722.png)

I have a full pcap, so can send it to you if needed.

Best regards,
Andrey

**Comment by TimEvens** [comment]
Thank you for raising this issue. Could you send me that pcap? I should be able to replay that on my side.

**Comment by v1shnya** [comment]
Hi Tim,Please, see pcap in attachment.More specifically I see an issue with vpnv4 routes.On 16 Sep 2022, at 15:03, Tim Evens ***@***.***> wrote:﻿
Thank you for raising this issue. Could you send me that pcap? I should be able to replay that on my side.

**Comment by v1shnya** [comment]
Sent it to tim@openbmp address

**Comment by TimEvens** [comment]
I replayed the PCAP and was able to reproduce and fix the issue. The issue is with the psql-app consumer obmp-java-message lib. I'll fix that shortly and update the container.

**Comment by v1shnya** [comment]
Perfect, thank you, Tim!

**Comment by TimEvens** [comment]
@v1shnya , I've committed the changes and updated the docker containers to resolve the issue. Can you try to upgrade, either via fresh install or the new [Upgrade](https://www.openbmp.org/install_config/live_upgrade.html) instructions?

**Comment by v1shnya** [comment]
Work like a charm!
